### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by x99percent** [sabeechen/hassio-google-drive-backup#26]
I honestly have no idea what causes this error, but it's happening regularly. The only thing I can think of is maybe it's something in my firewall config..?

Traceback (most recent call last):
  File "/app/backup/engine.py", line 95, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 310, in _checkForBackup
    self._syncSnapshots()
  File "/app/backup/engine.py", line 245, in _syncSnapshots
    drive_snapshots = self.drive.readSnapshots(self.folder_id)
  File "/app/backup/drive.py", line 144, in readSnapshots
    for child in self._iterateQuery(q="'{}' in parents".format(parent_id)):
  File "/app/backup/drive.py", line 231, in _iterateQuery
    response = self._retryDriveServiceCall(request)
  File "/app/backup/drive.py", line 160, in _retryDriveServiceCall
    return request.execute()
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1533, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by sabeechen** [comment]
There have been a few issues in the past leading to spotty connections to the Google api server googleapis.com (mainly DNS problems until this), but no real progress on what the cause is.

* Do you have anything that might be blocking the connection, eg pi-hole or another network wide ad-blocker, maybe custom DNS settings?
* Does it start working again eventually?  you can make it retry immediately by going to  ACTIONS-> "Sync Now" form the top menu.  The error dialog will hide itself within a few seconds if it syncs successfully.

You might try pining googleapis.com to make sure you can actually reach it from your network.

I'd like to be able to figure this out and provide a better error message when it happens.

**Comment by x99percent** [comment]
Seeing as how the googleapis.com name resolves to a wide range of IP addresses, is there any way the error message(s) could be changed to also contain the IP address the plugin is currently failing to reach?

**Comment by sabeechen** [comment]
I'll work on exposing this in the next release.  I'm not sure if the python network stack actually lets me inspect which IP is being used for a hostname (I think it picks one at random) but I can at least expose the full lists in the error dialog.  I've looked into it some, and it seems Google uses some kind of DNS magic to distribute load and give different geographical areas different servers to use so this is all a bit tricky to nail down.

**Comment by sabeechen** [comment]
I just released v0.94, which has this change.  With the update you should see a link to show Google's DNS information in the big red error dialog when it has trouble reaching the servers.  It also trys to ping each IP address and shows the result.

**Comment by x99percent** [comment]
Everything looks good as far as the DNS info, but I still get regular errors. I'm at a loss as to what could be causing the problem.

![Temp](https://user-images.githubusercontent.com/603416/57100712-a4d54500-6ced-11e9-9e40-97752c527c54.png)

**Comment by sabeechen** [comment]
In the latest release (v0.96.1) I've written a new library for communicating with Google Drive.  Eventually it will become the default, but you can enable it early by adding this to your add-on configure (can't be setup through the UI yet):
* `"drive_experimental": true`
* `"ignore_ipv6_addresses": true`

And then restarting the add-on.  I suspect it is likely to resolve this issue.

**Comment by sabeechen** [comment]
I havean't heard back in a while, but I recently released v0.97 which attempts to use known good DNS servers when it has trouble reaching Google Drive like this and seems to be working well for others.  If your're still runnign into problems with that verison, feel free to reopen this issue and I can look into it further.
