### ISSUE TITLE
Stopped addons not restarting

### ISSUE THREAD

**Issue by tungmeister** [sabeechen/hassio-google-drive-backup#263]
After updating to the latest version I enabled the stoping of mariadb and influxdb however nether restarted after the snapshot was taken - here's the backup log:
```
09-18 03:30:55 INFO Syncing Snapshots
09-18 03:30:56 INFO Stopping addon 'MariaDB'
09-18 03:31:03 INFO Stopping addon 'InfluxDB'
09-18 03:31:08 INFO Requesting a new snapshot
09-18 03:31:13 INFO Deleting 'Full Snapshot 2020-09-15 03:06:39' from Home Assistant
09-18 03:31:14 INFO Syncing Snapshots
09-18 03:31:18 INFO Backup directory changed
09-18 03:31:18 INFO Syncing Snapshots
09-18 04:03:42 INFO Snapshot finished
09-18 04:03:42 INFO Syncing Snapshots
09-18 04:03:43 INFO Uploading 'Full Snapshot 2020-09-18 03:30:55' to Google Drive
09-18 04:09:44 INFO Deleting 'Full Snapshot 2020-09-06 03:08:15' From Google Drive
09-18 04:09:45 INFO Backup directory changed
09-18 04:09:45 INFO Syncing Snapshots
```
At what point in the backup sequence should the addons have restarted? If it's meant to be once the entire snapshot is completed ~30 mins would be a long time for the database to be down.

**Comment by Ysbrand** [comment]
I see the same behavior. Both MariaDB as well as Influx dB are not started after the backup.

Can't really find that much evidence in the logs. My logs are at debug (not sure why) and the logfile apparently rolls over at some point.

**Comment by sabeechen** [comment]
It should start back up after the snapshot is finished, this addon doesn't get told when any other specific addon is being archived so the only choice it has is to stop it during the entire snapshot.  If you're thinking this really is something that should be implemented inside the the supervisor instead of the addon, I agree with you.

Could I have one of you take a snapshot, wait for it to finish, then use "Actions" > "Make a Bug report" and then paste the reports contents here?

**Comment by Ysbrand** [comment]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.114.4`
 Supervisor Version: `245`
 Supervisor Channel: `stable`
 Hassos Version: `5.1`
 Docker Version: `19.03.11`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2020-09-20T17:57:03.923941+00:00`
 Timezone: `Europe/Amsterdam`
 Failure Time: `Never`
 Last Good Sync: `2020-09-20T17:56:47.032121+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 5,
        "retained": 1,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-09-20T17:43:31Z",
        "size": "1.4 GB"
    },
    "GoogleDrive": {
        "snapshots": 13,
        "retained": 1,
        "deletable": 12,
        "name": "GoogleDrive",
        "latest": "2020-09-20T17:43:31Z",
        "size": "3.9 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 12,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "01:30",
    "Setting.GENERATIONAL_DAYS": 3,
    "Setting.GENERATIONAL_WEEKS": 3,
    "Setting.GENERATIONAL_MONTHS": 5,
    "Setting.GENERATIONAL_YEARS": 2,
    "Setting.STOP_ADDONS": "a0d7b954_influxdb,core_mariadb"
}
 ```
 ###### Addon Logs:
 ```
 09-20 19:56:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:31 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 88.78%
09-20 19:56:31 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-20 19:56:31 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:33 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 91.55%
09-20 19:56:34 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-20 19:56:34 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:36 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 94.32%
09-20 19:56:36 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-20 19:56:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:39 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 97.09%
09-20 19:56:39 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-20 19:56:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:41 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 99.86%
09-20 19:56:41 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-20 19:56:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy3yopUK4s6HkB1k7RUT7Pn_RqygWoD10TC7l8WKLpNBaZ-yjefWYxYBXi28yqmixwwOUXR2vncGedYR-7SpbE
09-20 19:56:44 DEBUG [backup.drive.drivesource] Uploading 20092020-1943 100.00%
09-20 19:56:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1GKAd8sEzY7JzvXe3jMDWJ6oqr__VWsIs/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-20 19:56:44 INFO [backup.drive.drivesource] Deleting 'Full Snapshot 2020-09-16 02:05:38' From Google Drive
09-20 19:56:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1Eobt80dLOy29WmuP1QlDytRiQL4oaHs6/?supportsAllDrives=true
09-20 19:56:45 INFO [backup.worker.watcher] Backup directory changed
09-20 19:56:45 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
09-20 19:56:45 INFO [backup.model.coordinator] Syncing Snapshots
09-20 19:56:45 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-20 19:56:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1OdvZfee7sD-OH83uRoipA3j4aWYYmZpv/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-20 19:56:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271OdvZfee7sD-OH83uRoipA3j4aWYYmZpv%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-20 19:56:47 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
09-20 19:56:47 INFO [backup.model.coordinator] Syncing Snapshots
09-20 19:56:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-20 19:56:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271OdvZfee7sD-OH83uRoipA3j4aWYYmZpv%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m20-09-20 17:46:43 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_mariadb[0m
[32m20-09-20 17:54:59 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mariadb[0m
[32m20-09-20 17:54:59 INFO (MainThread) [supervisor.snapshots] Snapshot 6481d58b store folders[0m
[32m20-09-20 17:54:59 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder media[0m
[32m20-09-20 17:54:59 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder media done[0m
[32m20-09-20 17:54:59 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local[0m
[32m20-09-20 17:54:59 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local done[0m
[32m20-09-20 17:54:59 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant[0m
[32m20-09-20 17:55:01 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done[0m
[32m20-09-20 17:55:01 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder share[0m
[32m20-09-20 17:55:01 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder share done[0m
[32m20-09-20 17:55:01 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl[0m
[32m20-09-20 17:55:01 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl done[0m
[32m20-09-20 17:55:05 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 6481d58b done[0m
[32m20-09-20 17:55:05 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:05 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:05 INFO (MainThread) [supervisor.api.security] /addons/a0d7b954_influxdb/start access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:08 INFO (SyncWorker_4) [supervisor.docker.addon] Start Docker add-on hassioaddons/influxdb-aarch64 with version 3.7.5[0m
[32m20-09-20 17:55:08 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:08 INFO (MainThread) [supervisor.api.security] /snapshots/6481d58b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:09 INFO (MainThread) [supervisor.api.security] /snapshots/3aa04bfc/remove access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:09 INFO (MainThread) [supervisor.snapshots] Removed snapshot file 3aa04bfc[0m
[32m20-09-20 17:55:09 INFO (MainThread) [supervisor.api.security] /snapshots/6481d58b/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:55:09 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 6481d58b[0m
[32m20-09-20 17:55:09 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_influxdb[0m
[32m20-09-20 17:55:10 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_influxdb[0m
[32m20-09-20 17:56:45 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:56:47 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-20 17:57:03 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2618, in _flush
    flush_context.transaction = transaction = self.begin(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 953, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 317, in _begin
    self._assert_active()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
2020-09-20 19:57:00 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
2020-09-20 19:57:00 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 433, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 484, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 502, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
2020-09-20 19:57:00 ERROR (SyncWorker_33) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'core-mariadb' (-3)")
(Background on this error at: http://sqlalche.me/e/13/e3q8)

 ```
 
 Ans a little bit more from the logs:
 09-20 19:42:46 INFO Syncing Snapshots
09-20 19:43:21 INFO Stopping addon 'InfluxDB'
09-20 19:43:25 INFO Stopping addon 'MariaDB'
09-20 19:43:31 INFO Requesting a new snapshot
09-20 19:55:05 INFO Snapshot finished
09-20 19:55:05 INFO Starting addon 'InfluxDB'
09-20 19:55:08 INFO Syncing Snapshots
09-20 19:55:09 INFO Deleting 'Full Snapshot 2020-09-20 02:06:00' from Home Assistant
09-20 19:55:09 INFO Uploading '20092020-1943' to Google Drive
09-20 19:56:44 INFO Deleting 'Full Snapshot 2020-09-16 02:05:38' From Google Drive
09-20 19:56:45 INFO Backup directory changed
09-20 19:56:45 INFO Syncing Snapshots
09-20 19:56:47 INFO Syncing Snapshots

So yes, it stops InfluxDB and MariaDB, but it only starts InfluxDB

**Comment by TeNpoLe21** [comment]
I'm seeing the same thing with MariaDB. Add-on stops but is never restarted.

**Comment by sabeechen** [comment]
It looks like stop addon feature is broken.  I'd recommend disabling it until I figure out whats wrong and make a new release.

**Comment by Ysbrand** [comment]
Just a bit further information:

Originally I had 2 items checked for auto stop/start: MariaDB, InfluxDB
- Only InfluxDB started after the snapshot

As MariaDB seemed to have a problem, I removed it from the list, and only enabled InfluxDB for autostop/start
- Now InfluxDB was not started anymore

**Comment by sabeechen** [comment]
I just released the addon version 0.102.0, which includes a fix for this.  Its now much more thorough in making sure that addons get started after a snapshot and also temporarily disables the newer watchdog feature when necessary.   Please let me know or reopen this issue if you run into any trouble with the new version.

Also just a reminder, to make Home Assistant see the new version right away go to "Supervisor" > "Add-on Store" > Three dots in the top right corner > "Reload"

**Comment by Ysbrand** [comment]
Hi,

Sorry for the late notice, but I just found your update.

I've tested this and all is well:

11-10 10:59:07 INFO Temporarily disabling watchdog for addon 'InfluxDB'
11-10 10:59:07 INFO Stopping addon 'InfluxDB'
11-10 10:59:12 INFO Temporarily disabling watchdog for addon 'MariaDB'
11-10 10:59:12 INFO Stopping addon 'MariaDB'
11-10 10:59:19 INFO Requesting a new snapshot
11-10 11:18:38 INFO Snapshot finished
11-10 11:18:39 INFO Syncing Snapshots
11-10 11:18:40 INFO Deleting 'Full Snapshot 2020-11-10 02:06:48' from Home Assistant
11-10 11:18:40 INFO Uploading 'Full Snapshot 2020-11-10 10:59:07' to Google Drive
11-10 11:18:59 INFO Starting addon 'InfluxDB'
11-10 11:19:02 INFO Starting addon 'MariaDB'
11-10 11:19:05 INFO Re-enabling watchdog for addon 'InfluxDB'
11-10 11:19:05 INFO Re-enabling watchdog for addon 'MariaDB'

Thanks for fixing this.

**Comment by URBANsUNITED** [comment]
Hi!

This issues came back for me!
I have no idea since when, but some of my addons do not restart after the backup.
Not all, only these:
08-01 13:37:54 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/core_mariadb/info
08-01 13:38:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/45df7312_zigbee2mqtt/info
08-01 13:38:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/5c53de3b_esphome/info
08-01 13:38:05 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/7094bb28_docker-wyze-bridge/info

All was working flawless before, maybe 2-3 Weeks since I have this problem.
Latest version installed. 0.108.2

Where can I look to help here?

Thanks

URBANsUNITED

**Comment by sabeechen** [comment]
I'd take a backup, and once its completed (verifying the addons didn't start back up) go to "Action"s > "Report a bug" in the addon and create a new issue with that bug report.
