### ISSUE TITLE
Latest version not correct?

### ISSUE THREAD

**Issue by jorojoro66** [sabeechen/hassio-google-drive-backup#365]
Still making 2 backups every night and still on V0.102.0, which according to the changelog is the latest version.

_Originally posted by @jorojoro66 in https://github.com/sabeechen/hassio-google-drive-backup/issues/340#issuecomment-803214303_

**Comment by jorojoro66** [comment]
Just completely deleted addon and reinstalled. Still the latest version is 0.102.0.
I will see tonight if it still makes 2 backups and report back.

**Comment by jorojoro66** [comment]
Last night still 2 backups. One at 2:00 without having this time set for backup. One at 3:00, as planned in addon.
How to get rid of the 2:00 backup?

**Comment by sabeechen** [comment]
On the snapshots "Add-on Store" page, could you go to the top right of the page click <kbd>...</kbd> > <kbd>Reload</kbd>?
If the new version doesn't show up, then go to the <kbd>System</kbd> page and look at the logs.  If it had trouble checking the latest verison, there should be some error message listed in the logs.  The latest published [changelog](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/CHANGELOG.md) definitely is for v0.103.1, So your supervisor is definitely not showing you the latest info.

This is likely the cause of the double snapshot problem, since the version you're using has a timing bug that could cause what you're seeing.

**Comment by jorojoro66** [comment]
This is what the log shows after your suggested action:

21-03-22 23:59:05 INFO (MainThread) [supervisor.store] Loading add-ons from store: 79 all - 0 new - 0 remove
21-03-22 23:59:05 INFO (MainThread) [supervisor.store] Loading add-ons from store: 79 all - 0 new - 0 remove

**Comment by jorojoro66** [comment]
Any news? Snapshots take double space now, which I’d like to avoid.
Very weird that I don’t see a more recent version.

**Comment by sabeechen** [comment]
I just released v0.104.1, which took me waaaaaaaay longer than I had hoped to release.  I appologize for my protracted silence.  Could you see if your supervisor is seeing the new version?

Also I'm realizing now that the problem might be that the supervisor is failing see _any_ updates because that Google Sheets addon config isn't parsed correctly.  Do you have any other custom repositories that might have a misconfigured addon?

**Comment by jorojoro66** [comment]
Thanks again.

Unfortunately upervisor still shows 0.102.0
All other addons give updates regularly, so it looks specific for this one.
